import { Player, Match, Court, Club, ClubCourt, CourtBooking } from "./types";

export const mockPlayers: Player[] = [
  {
    id: "1",
    name: "Rahul Sharma",
    age: 16,
    phone: "9876543210",
    club: "Delhi Sports Club",
    gender: "male",
    events: ["singles"],
  },
  {
    id: "2",
    name: "Priya Patel",
    age: 15,
    phone: "9876543211",
    club: "Mumbai Racquet Club",
    gender: "female",
    events: ["singles", "doubles"],
    partnerId: "4",
    partnerName: "Ananya Singh",
  },
  {
    id: "3",
    name: "Arjun Kumar",
    age: 17,
    phone: "9876543212",
    club: "Bangalore Sports Academy",
    gender: "male",
    events: ["singles"],
  },
  {
    id: "4",
    name: "Ananya Singh",
    age: 15,
    phone: "9876543213",
    club: "Mumbai Racquet Club",
    gender: "female",
    events: ["doubles"],
    partnerId: "2",
    partnerName: "Priya Patel",
  },
];

export const mockMatches: Match[] = [
  {
    id: "M001",
    code: "SPT2024001",
    player1: "Rahul Sharma",
    player2: "Arjun Kumar",
    eventType: "Men's Singles",
    category: "U17",
    court: 1,
    startTime: "09:00",
    endTime: "09:25",
    round: "R1",
    status: "ongoing",
  },
  {
    id: "M002",
    code: "SPT2024002",
    player1: "Priya Patel",
    player2: "Ananya Singh",
    eventType: "Women's Doubles",
    category: "U15",
    court: 2,
    startTime: "09:00",
    endTime: "09:30",
    round: "R1",
    status: "ongoing",
  },
  {
    id: "M003",
    code: "SPT2024003",
    player1: "Vikram Shah",
    player2: "Rohan Gupta",
    eventType: "Men's Singles",
    category: "Open",
    court: 3,
    startTime: "09:10",
    endTime: "09:35",
    round: "QF",
    status: "pending",
  },
];

export const mockCourts: Court[] = [
  {
    id: 1,
    currentMatch: mockMatches[0],
    nextMatch: {
      id: "M004",
      code: "SPT2024004",
      player1: "Player A",
      player2: "Player B",
      eventType: "Men's Singles",
      category: "U15",
      round: "R1",
      status: "pending",
    },
  },
  {
    id: 2,
    currentMatch: mockMatches[1],
    nextMatch: undefined,
  },
  {
    id: 3,
    currentMatch: undefined,
    nextMatch: mockMatches[2],
  },
];

export const mockClubs: Club[] = [
  {
    id: "club1",
    name: "Delhi Sports Club",
    logo: "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=200",
    location: "New Delhi, India",
    about: "Premier sports club with world-class facilities and professional coaching staff.",
    playerCount: 45,
    courts: [
      { id: "c1", name: "Court 1", type: "indoor", clubId: "club1" },
      { id: "c2", name: "Court 2", type: "outdoor", clubId: "club1" },
      { id: "c3", name: "Court 3", type: "indoor", clubId: "club1" },
    ],
    contactInfo: "+91 98765 43210",
    socialLinks: {
      website: "https://delhisportsclub.com",
      instagram: "@delhisportsclub",
    },
    createdBy: "user1",
    members: ["1", "2", "3"],
  },
  {
    id: "club2",
    name: "Mumbai Rack Club",
    logo: "https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=200",
    location: "Mumbai, India",
    about: "Elite club focusing on competitive tournaments and player development.",
    playerCount: 32,
    courts: [
      { id: "c4", name: "Court A", type: "indoor", clubId: "club2" },
      { id: "c5", name: "Court B", type: "outdoor", clubId: "club2" },
    ],
    contactInfo: "+91 98765 43211",
    createdBy: "user2",
    members: ["2", "4"],
  },
  {
    id: "club3",
    name: "Bangalore Sports Academy",
    logo: "https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?w=200",
    location: "Bangalore, India",
    about: "Modern academy with state-of-the-art training facilities and expert coaches.",
    playerCount: 28,
    courts: [
      { id: "c6", name: "Arena 1", type: "indoor", clubId: "club3" },
      { id: "c7", name: "Arena 2", type: "indoor", clubId: "club3" },
      { id: "c8", name: "Outdoor Court", type: "outdoor", clubId: "club3" },
    ],
    contactInfo: "+91 98765 43212",
    socialLinks: {
      website: "https://bangaloresportsacademy.com",
      facebook: "BangaloreSportsAcademy",
    },
    createdBy: "user3",
    members: ["3"],
  },
];

export const mockBookings: CourtBooking[] = [
  {
    id: "b1",
    courtId: "c1",
    courtName: "Court 1",
    clubId: "club1",
    clubName: "Delhi Sports Club",
    userId: "user1",
    userName: "Rahul Sharma",
    date: "2024-12-25",
    startTime: "10:00",
    endTime: "11:00",
    status: "confirmed",
  },
  {
    id: "b2",
    courtId: "c4",
    courtName: "Court A",
    clubId: "club2",
    clubName: "Mumbai Racquet Club",
    userId: "user2",
    userName: "Priya Patel",
    date: "2024-12-25",
    startTime: "14:00",
    endTime: "15:30",
    status: "confirmed",
  },
];
